### ISSUE TITLE
I get these errors, can someone help?

### ISSUE THREAD

**Issue by LFGaming** [Surya0023/bluedoser#3]
When using the program, i get these errors,
![image](https://user-images.githubusercontent.com/38732192/117550386-63947000-b040-11eb-905e-e50b1651f004.png)

Could someone help me on fixing this problem?

**Comment by BanementI** [comment]
If you're unable to understand the simple errors it's throwing, no offense but you really need to spend some time learning about the terminal...
<details>
  <summary>Click me for solution</summary>
  
  Install xterm. That's it. Please spend some of your time learning about how to use bash and the terminal so you can solve these issues on your own in the future.
  
</details>

**Comment by LFGaming** [comment]
I am indeed learning about the terminal more the last time :) but thanks

**Comment by Mifaxav** [comment]
sudo apt-get install xterm
